// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKOco1rmop7oZcsI1NHVipvfC5IpGYIyE',
    appId: '1:585508054843:android:f7d188790f4c558b2c391e',
    messagingSenderId: '585508054843',
    projectId: 'aplikacja-promocje-87e96',
    databaseURL: 'https://aplikacja-promocje-87e96-default-rtdb.firebaseio.com',
    storageBucket: 'aplikacja-promocje-87e96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FaRdP7Qm7nQmx7Y65leydH05-ihSKdA',
    appId: '1:585508054843:ios:19d5334cdfe424182c391e',
    messagingSenderId: '585508054843',
    projectId: 'aplikacja-promocje-87e96',
    databaseURL: 'https://aplikacja-promocje-87e96-default-rtdb.firebaseio.com',
    storageBucket: 'aplikacja-promocje-87e96.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
